name: cleo-pe2
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.43
  - binutils_linux-64=2.43
  - brian2=2.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - colorama=0.4.6
  - contourpy=1.3.2
  - cpython=3.12.11
  - cycler=0.12.1
  - cython=3.1.2
  - docopt=0.6.2
  - fonttools=4.58.2
  - freetype=2.13.3
  - gcc_impl_linux-64=13.3.0
  - gcc_linux-64=13.3.0
  - gitdb=4.0.12
  - gitpython=3.1.44
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gsl=2.8
  - gxx_impl_linux-64=13.3.0
  - gxx_linux-64=13.3.0
  - jinja2=3.1.6
  - jsonpickle=4.1.1
  - kernel-headers_linux-64=3.10.0
  - kiwisolver=1.4.8
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.24
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=13.3.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsanitizer=13.3.0
  - libsqlite=3.50.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=13.3.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - matplotlib-base=3.10.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munch=4.0.0
  - munkres=1.1.4
  - ncurses=6.5
  - openjpeg=2.5.3
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.3.0
  - patsy=1.0.1
  - pillow=11.2.1
  - pip=25.1.1
  - pthread-stubs=0.4
  - py-cpuinfo=9.0.0
  - pyparsing=3.2.3
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - qhull=2020.2
  - readline=8.2
  - sacred=0.8.5
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - smmap=5.0.2
  - statsmodels=0.14.4
  - sympy=1.14.0
  - sysroot_linux-64=2.17
  - tk=8.6.13
  - typing_extensions=4.14.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - wheel=0.45.1
  - wrapt=1.17.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.7
  - pip:
      - attrs==23.2.0
      - blosc2==3.3.4
      - brian2tools==0.3
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - cleosim==0.18.1
      - idna==3.10
      - importlib-resources==6.5.2
      - jaxtyping==0.2.38
      - libneuroml==0.6.7
      - lxml==5.4.0
      - markdown-strings==3.4.0
      - msgpack==1.1.0
      - natsort==8.4.0
      - ndindex==1.10.0
      - neo==0.12.0
      - networkx==3.5
      - numexpr==2.11.0
      - numpy==2.2.6
      - platformdirs==4.3.8
      - pylems==0.6.8
      - quantities==0.16.2
      - requests==2.32.4
      - scipy==1.14.0
      - setuptools-scm==8.3.1
      - tables==3.10.2
      - tklfp==0.2.1
      - urllib3==2.4.0
      - wadler-lindig==0.1.6
      - wslfp==0.2.3
