version: '3'

vars:
  FIRING_RATES_SD: [0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2]
  PARAM_OVERRIDES: '{{.PARAM_OVERRIDES | default ""}}'

tasks:

  default:
    desc: Run all experiments and plot the results
    deps:
      - task: run_all
    cmds:
      - task: plot

  test:
    desc: Run all with large timestep to test pipeline
    deps:
      - task: run_all
        vars:
          PARAM_OVERRIDES: 'params.timestep_ms_=1'
    cmds:
      - task: plot

  plot:
    desc: Plot the results of the experiments
    sources:
      - plot_parameter_sweep.py
      - results/base_mean_sd.txt
      - results/Spiking_model_baseline/results.pkl
      - for: { var: FIRING_RATES_SD, as: FR_SD }
        file: results/Spiking_model_PIcontrol_PV_rt_tSD_{{.FR_SD}}/results.pkl
    generates:
      - results/*.svg
      - results/*.png
      - results/*.pdf
    cmds:
      - python plot_parameter_sweep.py '{{.FIRING_RATES_SD | join ","}}'

  run_all:
    desc: Run baseline then control experiments in parallel
    deps:
      - task: get_targets_from_baseline
        vars:
          PARAM_OVERRIDES: '{{.PARAM_OVERRIDES}}'
    cmds:
      - task: run_all_ctrl
        vars:
          PARAM_OVERRIDES: '{{.PARAM_OVERRIDES}}'

  run_all_ctrl:
    internal: true
    deps:
      - for: {var: FIRING_RATES_SD, as: FR_SD}
        task: run_ctrl
        vars:
          FR_SD: '{{.FR_SD}}'
          PARAM_OVERRIDES: '{{.PARAM_OVERRIDES}}'

  get_targets_from_baseline:
    internal: true
    desc: Get the mean and standard deviation of the base firing rate
    deps:
      - task: run
        vars:
          FIRING_RATE: -1
          OUTDIR: results/Spiking_model_baseline
          PARAM_OVERRIDES: '{{.PARAM_OVERRIDES}}'
    sources:
      - results/Spiking_model_baseline/results.pkl
      - get_targets_from_baseline.py
    generates:
      - results/base_mean_sd.txt
    cmds:
      - python get_targets_from_baseline.py  results/Spiking_model_baseline/results.pkl

  run:
    desc: Run a single experiment for a target firing rate
    vars:
      FIRING_RATE: '{{.FIRING_RATE | default -1}}'
    sources:
      - Spiking_model_cleo.py
    generates:
      - "{{.OUTDIR}}/results.pkl"
    cmds:
      - python Spiking_model_cleo.py -F {{.OUTDIR}} with target_firing_rate={{.FIRING_RATE}} {{.PARAM_OVERRIDES}}
      # link to latest run (need to find dynamically)
      - ln -sf $(pwd)/{{.OUTDIR}}/$(find {{.OUTDIR}} -maxdepth 1 -type d -regex '.*/[0-9]+' | awk -F/ '{print $NF}' | sort -n | tail -1)/results.pkl {{.OUTDIR}}


  run_ctrl:
    internal: true
    vars:
      FIRING_RATE:
        sh: python firing_rate_sd_to_hz.py {{.FR_SD}}
      OUTDIR: results/Spiking_model_PIcontrol_PV_rt_tSD_{{.FR_SD}}
    sources:
      - results/base_mean.txt
      - results/base_sd.txt
    generates:
      - "{{.OUTDIR}}/results.pkl"
    cmds:
      - task: run
        vars:
          FIRING_RATE: '{{.FIRING_RATE}}'
          OUTDIR: '{{.OUTDIR}}'
          PARAM_OVERRIDES: '{{.PARAM_OVERRIDES}}'


  plot_exp:
    desc: Produce detailed plots of a single experiment
    sources:
      - plot_essentials.py
      - plot_Spikingmodel_stripped.py
      - '{{.OUTDIR}}/results.pkl'
    cmds:
      - python plot_Spikingmodel_stripped.py {{.OUTDIR}}
      - python plot_essentials.py {{.OUTDIR}}


  plot_all_exps:
    deps:
      - for: { var: FIRING_RATES_SD, as: FR_SD }
        task: plot_exp
        vars:
          OUTDIR: results/Spiking_model_PIcontrol_PV_rt_tSD_{{.FR_SD}}
      - task: plot_exp
        vars:
          OUTDIR: results/Spiking_model_baseline
    
      